"""initial_tables

Revision ID: f33b6601b19b
Revises: 
Create Date: 2025-12-03 23:13:16.550703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33b6601b19b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Room',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=True),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('code')
    )
    op.create_table('GiftAssignment',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('giver_id', sa.BigInteger(), nullable=True),
    sa.Column('receiver_id', sa.BigInteger(), nullable=True),
    sa.Column('room_code', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['giver_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['room_code'], ['Room.code'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('Wish',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('room_code', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['room_code'], ['Room.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('user_room',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('room_code', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['room_code'], ['Room.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_room')
    op.drop_table('Wish')
    op.drop_table('GiftAssignment')
    op.drop_table('Room')
    op.drop_table('User')
    # ### end Alembic commands ###
